name: Tagged Release

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    # Arch Matrix
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64]
        short-os: [win, osx, linux]
        include:
          - short-os: osx
            os: macos-latest
            rust-os: apple-darwin
            tauri-bundles: dmg,app
            tauri-create-updater: true
          - short-os: win
            os: windows-latest
            rust-os: pc-windows-msvc
            tauri-bundles: nsis
            tauri-create-updater: true
          - short-os: linux
            os: ubuntu-24.04
            rust-os: unknown-linux-gnu
            tauri-bundles: deb,rpm
            tauri-create-updater: false
          - arch: x64
            rust-arch: x86_64
          - arch: arm64
            rust-arch: aarch64
          - short-os: linux
            arch: arm64
            os: ubuntu-24.04-arm
    uses: ./.github/workflows/reusable-tauri.yml
    with:
      arch: ${{ matrix.arch }}
      rust-arch: ${{ matrix.rust-arch }}
      os: ${{ matrix.os }}
      short-os: ${{ matrix.short-os }}
      rust-os: ${{ matrix.rust-os }}
      tauri-bundles: ${{ matrix.tauri-bundles }}
      publish-release: ${{ true }}
      tauri-create-updater: ${{ matrix.tauri-create-updater }}
      generate-aur-defs: ${{ matrix.short-os == 'linux' && matrix.arch == 'x64' }}
      api-ref: 'v0.22.4'
    secrets: inherit # Pass all secrets
  create-github-release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Checkout Sauna UI
        uses: actions/checkout@v4
      - name: Publish Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: gh release edit ${{ needs.build.outputs.release-tag }} --latest --draft=false
  create-aur-package:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-24.04
    needs: build
    continue-on-error: true
    env:
      AUR_PACKAGE_NAME: sauna-sim
    steps:
      - name: Checkout Sauna UI
        uses: actions/checkout@v4
      - name: Download AUR Artifacts
        uses: actions/download-artifact@v4
        with:
          name: aur-package-defs
          path: ${{ github.workspace }}/aurdefs
      - name: Add Deb Checksums
        shell: pwsh
        run: |
          (Get-Content ${{ github.workspace }}/aurdefs/PKGBUILD).Replace('@AUR_DEB_SHA256_AMD64@', '${{ needs.build.outputs.deb-sha256-x64 }}') | Set-Content ${{ github.workspace }}/aurdefs/PKGBUILD
          (Get-Content ${{ github.workspace }}/aurdefs/PKGBUILD).Replace('@AUR_DEB_SHA256_ARM64@', '${{ needs.build.outputs.deb-sha256-arm64 }}') | Set-Content ${{ github.workspace }}/aurdefs/PKGBUILD
      - name: Publish AUR Package
        uses: KSXGitHub/github-actions-deploy-aur@v3
        with:
          pkgname: ${{ env.AUR_PACKAGE_NAME }}
          pkgbuild: ${{ github.workspace }}/aurdefs/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519
          assets: |
            ${{ github.workspace }}/aurdefs/*.install

  cleanup-github-release:
    if: failure()
    runs-on: ubuntu-24.04
    needs: [build, create-github-release]
    steps:
      - name: Checkout Sauna UI
        uses: actions/checkout@v4
      - name: Remove Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: gh release delete ${{ needs.build.outputs.release-tag }} -y
