name: Tagged Release

on:
  push:
    tags: [ "v*" ]

jobs:
  build:
    # Arch Matrix
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, arm64] #x86, arm
        os: [macos-latest, windows-latest, ubuntu-22.04]
        include:
          - os: macos-latest
            short-os: osx
            rust-os: apple-darwin
            tauri-bundles: dmg
          - os: windows-latest
            short-os: win
            rust-os: pc-windows-msvc
            tauri-bundles: nsis
          - os: ubuntu-22.04
            short-os: linux
            rust-os: unknown-linux-gnu
            tauri-bundles: deb
#          - arch: x86
#            rust-arch: i686
          - arch: x64
            rust-arch: x86_64
#          - arch: arm
#            rust-arch: armv7
          - arch: arm64
            rust-arch: aarch64
#          - os: ubuntu-latest
#            arch: arm
#            rust-target-suffix: eabihf
        exclude:
#          - os: windows-latest
#            arch: arm
#          - os: ubuntu-latest
#            arch: x86
#          - os: macos-latest
#            arch: x86
#          - os: macos-latest
#            arch: arm
          - os: windows-latest
            arch: arm64
          - os: ubuntu-22.04
            arch: arm64
    uses: ./.github/workflows/reusable-tauri.yml
    with:
      arch: ${{ matrix.arch }}
      rust-arch: ${{ matrix.rust-arch }}
      os: ${{ matrix.os }}
      short-os: ${{ matrix.short-os }}
      rust-os: ${{ matrix.rust-os }}
      tauri-bundles: ${{ matrix.tauri-bundles }}
      rust-target-suffix: ${{ matrix.rust-target-suffix }}
      upload-bundle-artifacts: ${{ true }}
      api-ref: 'v0.20.0'
    secrets: inherit # Pass all secrets

  create-github-release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')}}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Download Installers
        uses: actions/download-artifact@v3
        with:
          name: installers
          path: ${{ github.workspace }}/installers
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ${{ github.workspace}}/installers/*